- hosts: "{{ variable_host | default('server') }}"
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www/app
  tasks:
    - name: Synchronize static files
      synchronize:
        src: ../static/
        dest: /var/www/app/static
    - name: Synchronize build files
      synchronize:
        src: ../dist/
        dest: /var/www/app
    - name: Synchronize build files for sab
      synchronize:
        src: ../dist/
        dest: /var/www/app/sab
    - name: Synchronize executable files
      synchronize:
        src: ../rustserver/target/release/pybook-rustserver
        dest: /app/pybook-rustserver
    - name: Restart rust server
      service:
        name: pybook-rustserver
        state: restarted
