- hosts: all
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www/app
  tasks:
    - name: Synchronize static files
      synchronize:
        src: ../static/
        dest: /var/www/app/static
    - name: Synchronize build files
      synchronize:
        src: ../dist/
        dest: /var/www/app
    - name: Synchronize build files for nosab
      synchronize:
        src: ../dist/
        dest: /var/www/app/nosab
    - name: Synchronize executable files
      synchronize:
        src: ../rustserver/target/release/pybook-rustserver
        dest: /app/pybook-rustserver
    - name: Synchronize demo notebooks
      synchronize:
        src: ../notebooks/
        dest: /app/notebooks
    - name: Restart rust server
      service:
        name: pybook-rustserver
        state: restarted
