- hosts: "{{ variable_host | default('server') }}"
  vars:
    server_name: "{{ inventory_hostname }}"
    document_root: /var/www/app
  tasks:
    - name: Create app directory
      file:
        path: /app
        state: directory
    - name: Create mailjet keys file
      copy:
        dest: /app/mailjet.keys
        content: |
          {{ mailjet_apikey }}
          {{ mailjet_secret }}
          {{ feedback_sender }}
          {{ feedback_name }}
          {{ feedback_destination }}
    - name: Create rust service
      copy:
        src: pybook-rustserver.service
        dest: /etc/systemd/system/pybook-rustserver.service
    - name: Enable PyBook rust service
      service:
        name: pybook-rustserver.service
        enabled: yes
    - name: Ensure Nginx is at the latest version
      apt: name=nginx state=latest
    - name: Allow Nginx through ufw firewall
      ufw:
        rule: allow
        name: Nginx Full
        state: enabled
    - name: Setup Nginx appserver site
      template:
        src: ../nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx
    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
    - name: Start Nginx
      service:
          name: nginx
          state: started

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
